#!/bin/bash

if [ -z "${APPTAINER_ENVIRONMENT}" ]; then
    echo "This script cannot be run directly and must be started by the application container"
    exit 1
fi

echo "DRI in container:"
ls -alr /dev/dri
echo "DISPLAY in container: '${DISPLAY}'"

ls -al /tmp/.X11-unix

. ${pyenv-/pyenv/venv/bin/activate}
cd testgl

python cube.py
python hello_pybullet.py
