#!/bin/bash -ex

# Copyright 2022 CNRS-LAAS
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Author: David Gauchard

temp=/tmp/test-venv-deleteme-$$

python3 -m venv ${temp}
pyenv=${temp}/bin/activate
. ${pyenv}

cd testgl
pip install -r requirements.txt
../gputainer.postinstall
cd ..

set +e
. ./run-in-container.bash

echo "Play with me then exit:"
bash

rm -rf ${temp}
