#!/bin/bash

. ./env.sh

if [ ! -z "${SLURM_JOB_NAME}" ]; then
    echo "This script must NOT be run with sbatch:"
    echo "  ./$0"
    exit 1
fi

echo "Starting watcher"

#####################################
if [ -r "${watcher}" ]; then
    echo "A watcher is already started, please delete its file first" 1>&2
    echo "  rm ${watcher}" 1>&2
    exit 1
fi
touch ${watcher}
(
    while [ -r ${watcher} ]; do
        sleep 1
        for script in ${header}*sbatch; do
            if [ -r "${script}" ]; then
                mv ${script} ${script}-started
                # secondary submitter
                sbatch ${script}-started
            fi
        done
    done
) >& /dev/null </dev/null & pid=$!
#####################################

echo Watdhdog is started with pid ${pid}

# primary submitter
sbatch 3-generator "$@"
