#!/bin/bash

# Copyright 2022 CNRS-LAAS
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Author: David Gauchard

set -ex

extpython=true

APPDIR=${APP%/*}
APPNAME=${APP##*/}

echo APP=${APP}
echo APPDIR=${APPDIR}
echo APPNAME=${APPNAME}

if [ -z "${APP}" ]; then
    echo "\${APP} must point to an application directory (environment.yaml, requirements.txt)"
    exit 1
fi

if ${extpython}; then
    opts="--sandbox --bind ${APPDIR}/generated/PYTHAINER:/pyenv"
    mkdir -p ${APPDIR}/generated/PYTHAINER
fi

if [ ! -x ${APPDIR}/user-postinstall ]; then
    echo "Could not find an executable shell script '${APPDIR}/user-postinstall'"
    echo "(an empty one may be created)"
    exit 1
fi

if [ -z "${NVIDIA}" ]; then
    echo "shell variable 'NVIDIA' should list ubuntu packages (like 'libnvidia-gl-510 nvidia-utils-510' or 'nvidia-340')"
    exit 1
fi

# use apt-cacher if locally installed
[ -d /etc/apt-cacher ] && export APPTAINERENV_APT_PROXY=http://$(hostname):3142

# exports apptainer
export APPTAINER_APPDIR="${APPDIR}"
export APPTAINERENV_NVIDIA_PKG="${NVIDIA}"
export APPTAINERENV_APPDIR="${APPDIR}"
export APPTAINERENV_APPNAME="${APPNAME}"
export APPTAINERENV_NEED_CUDNN="${NEED_CUDNN}"  # empty, or 10.2 or 11.6 only are available at the time of writing

mkdir -p ${APPDIR}/generated
cd ${APPDIR}
apptainer build ${opts} --bind ${PWD}/../__gputainer/debs:/debs --bind /net:/net --bind /local:/local ${APPDIR}/generated/${APPNAME}.sifdir ../__gputainer/app.def 2>&1 | tee log-build-$(date +%y-%m-%d-%H-%M-%S)
