#!/bin/bash

sif=`cd generated; echo *.sif`
if [ ! -d "generated/${sif}" ]; then
    echo "generated/${sif}/ is not existing!"
    exit 1
fi

set -ex

#rsync -a generated/PYTHAINER/* generated/${sif}/pyenv/
#sudo apptainer build ../${sif} generated/${sif}

mkdir -p generated/${sif}/pyenv/
mv generated/PYTHAINER/{app,conda} generated/${sif}/pyenv/
sudo apptainer build ../${sif} generated/${sif}
mv generated/${sif}/pyenv/{app,conda} generated/PYTHAINER/
