#!/bin/bash

sif=`cd generated; echo *.sif`
if [ ! -d "generated/${sif}" ]; then
    echo "generated/${sif}/ is not existing!"
    exit 1
fi

set -ex

rsync -a generated/PYTHAINER/* generated/${sif}/pyenv/
sudo apptainer build ../${sif} generated/${sif}
