#!/bin/bash -e

if [ -z "${1}" ]; then
    run=$(pwd)/run-in-container
else
    run="${@}"
fi

APPDIR=${PWD}/generated
APPNAME=${PWD##*/}

echo APPDIR=${APPDIR}
echo APPNAME=${APPNAME}

# passing CUDA_VISIBLE_DEVICES
# set it to 0 (arbitrary) if not currently set
export APPTAINERENV_CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES-0}

if true; then
    # map /tmp from sub-tmp with linked X11 socket
    tmp=/tmp/apptainer-tmp-$(date +%y-%m-%d-%H-%M-%S)
    mkdir -p ${tmp}/.X11-unix
    ln /tmp/.X11-unix/* ${tmp}/.X11-unix/
else
    # share /tmp and X11 socket
    tmp=/tmp
fi

echo "DRI on host:"
ls -alr /dev/dri
echo "DISPLAY on host: '${DISPLAY}'"

export APPTAINERENV_MYHOME=${HOME}
time apptainer exec --nv --writable --bind $(pwd)/generated/PYTHAINER:/pyenv --bind $(pwd):/hostpwd --bind /net:/net --bind /local:/local --bind ${tmp}:/tmp generated/${APPNAME}.sif $(pwd)/../__gputainer/user-run-prepare ${run}
