#!/bin/bash

set -e
mkdir transportable

APPNAME=${PWD##*/}

sifdir=`cd generated; echo ${APPNAME}.sifdir`
if [ ! -d "generated/${sifdir}/." ]; then
    echo "generated/${sifdir}/ is not existing!"
    exit 1
fi

# vnc runner is the entry point
cp ../__gputainer/runvnc transportable/${APPNAME}.runme
chmod +x transportable/${APPNAME}.runme

# duplicate runner in container
cp run-in-container transportable/

# link the application directory which is,
# on purpose, not internal to the container
ln -s ../${APPNAME} transportable/

# create a simple slurm file skeleton
sbatchfile=transportable/slurm.sbatch
[ -r ${sbatchfile} ] || cat << EOF > ${sbatchfile}
#!/bin/sh
#SBATCH --job-name=${APPNAME}
#SBATCH please-fille-me-with-your-options

# run application with optional custom executable
# (or ./run-in-container will be executed)
./${APPNAME}.runme "\$@"
EOF

# temporarily move pyenv/ content to sifdir
mkdir -p generated/${sifdir}/pyenv/
trap 'mv generated/${sifdir}/pyenv/* generated/PYTHAINER/' EXIT
mv generated/PYTHAINER/* generated/${sifdir}/pyenv/

# build the sif container image
sif=${sifdir%*dir}
apptainer build transportable/${sif} generated/${sifdir}
chmod -x transportable/${sif}

# the above 'trap' will move pyenv/ content back to PYTHAINER/
