#!/bin/bash

APPNAME=${PWD##*/}

sifdir=`cd generated; echo ${APPNAME}.sifdir`
if [ ! -d "generated/${sifdir}/." ]; then
    echo "generated/${sifdir}/ is not existing!"
    exit 1
fi

trap "mv generated/${sifdir}/pyenv/{app,conda} generated/PYTHAINER/" EXIT

mkdir -p transportable generated/${sifdir}/pyenv/
cp ../__gputainer/runvnc transportable/${APPNAME}.runme
cp run-in-container transportable/
chmod +x transportable/${APPNAME}.runme
mv generated/PYTHAINER/{app,conda} generated/${sifdir}/pyenv/
apptainer build transportable/${sifdir%*dir} generated/${sifdir}
[ -x transportable/${sifdir%*dir} ] && chmod -x transportable/${sifdir%*dir}
