#!/bin/bash

# $HOME can be an artificial place, and
# - it is not kept up through apptainer
# - it is forbidden to set it up via APPTAINERENV_HOME
# so it is transmitted through APPTAINERENV_MYHOME:
if [ -z "${MYHOME}" ]; then
    echo "\$MYHOME (from APPTAINERENV_MYHOME) should be set!"
else
    export HOME=${MYHOME}
fi

"$@"
