#!/bin/sh

# first get ros_cosyplan, which includes cosypose's environment.yaml
if [ ! -r ros_cosypose/README.md ]; then
    git clone git@gitlab.laas.fr:cosyplan/ros_cosypose.git
fi

# use cosypose setup procedure
. ../cosypose/00-setup-env
. ./00-setup-env.vars.sh
