#!/bin/bash

# Copyright 2022 CNRS-LAAS
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Author: David Gauchard

if [ -z "${APPTAINER_ENVIRONMENT}" ]; then
    echo "This script cannot be run directly and must be started by the application container"
    exit 1
fi

. /pyenv/conda/etc/profile.d/conda.sh
conda activate /pyenv/app

# pybullet wants EGL_VISIBLE_DEVICES
export EGL_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES%%,*}    # example: 2,3,4 => 2

# cuda debugging
#export CUDA_LAUNCH_BLOCKING=1

echo inside apptainer DISPLAY=${DISPLAY}
echo CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
echo EGL_VISIBLE_DEVICES=${EGL_VISIBLE_DEVICES}
ls -alr /dev/dri

icewm & wm=$!

# show cuda is running
python -c 'import torch;print("torch.__version__=", torch.__version__, "\ntorch.cuda.device_count()=", torch.cuda.device_count(), "\ntorch.cuda.is_available()=", torch.cuda.is_available(), "\ntorch.version.cuda=", torch.version.cuda, "\ntorch.backends.cudnn.version()=", torch.backends.cudnn.version());'

if true; then
    cd cosypose
    # building but not installing because apptainer filesystem might be not writable
    [ -d build ] || python setup.py build
    (cd deps/bullet3; [ -d build ] || python setup.py build)
    (cd deps/job-runner; [ -d build ] || python setup.py build)
    (cd ../ros_cosypose; rm -rf build; python setup.py build)
    # path is necessary
    pylib=$(cd build; ls | grep ^lib | head -1)
    export PYTHONPATH=$(pwd)/build/${pylib}:$(pwd)/deps/bullet3/build/${pylib}:$(pwd)/deps/job-runner/build/${pylib}:${PYTHONPATH}
    export LD_LIBRARY_PATH=$(pwd)/build/${pylib}:$(pwd)/deps/bullet3/build/${pylib}:$(pwd)/deps/job-runner/build/${pylib}:${LD_LIBRARY_PATH}
    cd ..
else
    # cosypose is not integrated into apptainer image to allow for development
    (cd cosypose; [ -d build ] || python setup.py install)
    (cd cosypose/deps/bullet3; [ -d build ] || python setup.py install)
    (cd cosypose/deps/job-runner; [ -d build ] || python setup.py install)
    (cd ros_cosypose; [ -d build ] || python setup.py install)
fi

(
    cd ros_cosypose
    catkin clean -b -y || true
    catkin build
)

source ros_cosypose/devel/setup.bash
export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:$(pwd)/ros_cosypose
export PATH=$(pwd)/ros_cosypose/scripts:${PATH}

roslaunch ros_cosypose/launch/singleview_loop.launch debug:=true bringup_camera:=true || true

ret=$?
kill -9 $wm
(exit $ret)
