#!/bin/bash -ex

echo POSTINSTALL: setup ros-cosypose

. /pyenv/conda/etc/profile.d/conda.sh
conda activate /pyenv/app

apt -y install make   # for catkin

cd /hostpwd/ros_cosypose
catkin clean -b -y || true
catkin build

cd /hostpwd/generated
[ -L ros_cosypose.sifdir ] || ln -s cosypose.sifdir ros_cosypose.sifdir
