#!/bin/bash -ex

echo POSTINSTALL: setup ros-cosypose

. /pyenv/conda/etc/profile.d/conda.sh
conda activate /pyenv/app

apt -y install make   # for catkin

cd /hostpwd/ros_cosypose/ros_cosypose
catkin clean -b -y
catkin build

cd /hostpwd/ros_cosypose/generated
[ -L ros_cosypose.sif ] || ln -s cosypose.sif ros_cosypose.sif
