#!/bin/sh

if [ ! -r 00-setup-env.vars.sh ]; then
    echo "====================================================================================="
    echo "Copying default environment template, please review and adjust '00-setup-env.vars.sh'"
    echo "then restart me ($0)"
    echo "====================================================================================="
    cp 00-setup-env.vars-template.sh 00-setup-env.vars.sh
    exit 0
fi

. ./00-setup-env.vars.sh

if [ ! -r cosypose/README.md ]; then
    git clone ${cosypose_branch} ${cosypose}
    (cd cosypose; git submodule update --init)
    (cd cosypose; for p in ../patches/*.patch; do patch -Np1 < ${p}; done)

    [ -z "${condaenv}" ] || cp ${condaenv} cosypose/environment.yaml
    ln -s ${local_data} cosypose/local_data
fi
