#!/bin/sh -e

echo "Running T-LESS test to reproduce Y. Labbé results on CosyPose"

EXEC="cosypose"
GPU_REQUIRED=true

. /pfcalcul/tools/sbatchHelpers3.sh

jobMessage=$(
######################### SBATCH launcher
#########################     #SBATCH --option        # <= this is an enabled paramater
#########################     ##SBATCH --option       # <= this is a disabled parameter
sbatch ${sbatchopt} << eof
#!/bin/bash
#SBATCH --job-name=test_tless
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:${gpu}
#SBATCH --mail-type=ALL
#SBATCH --output=stdout.txt
#SBATCH --error=stderr.txt

./2-runvnc

eof
)

showSubmitted
