#!/bin/bash

# Copyright 2022 CNRS-IRIT
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Author: Elliot Maître

if [ ! -z "${SLURM_JOB_NAME}" ]; then
    echo "This script must NOT be run with sbatch:"
    echo "  ./$0"
    exit 1
fi

. ./environment.sh

if [ -z "${watcher}" ]; then
    echo "\"watcher\" variable is empty in config file environment.sh"
    exit 1
fi
if [ -z "${header}" ]; then
    echo "\"header\" variable is empty in config file environment.sh"
    exit 1
fi

echo "Starting watcher"

#####################################
# start watcher:
# - check for "${header}*sbatch" files
# - submt them with sbatch
# - stop when "${watcher}" is removed

if [ -r "${watcher}" ]; then
    echo "A watcher is already started, please delete its file first:" 1>&2
    echo "  rm ${watcher}" 1>&2
    exit 1
fi

touch ${watcher}

(
    while [ -r ${watcher} ]; do
        sleep 1
        for script in ${header}*sbatch; do
            if [ -r "${script}" ]; then
                mv ${script} ${script}-started
                # secondary submitter
                sbatch ${script}-started
            fi
        done
    done
) >& /dev/null </dev/null & pid=$!

echo Watchdog is started with pid ${pid}

#####################################
# start job generator

# primary submitter
sbatch 3-generator "$@"
