#!/bin/bash
#SBATCH --job-name=genlauncher
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=gpu
#SBATCH --mail-type=ALL
#SBATCH --output=stdout-%j.txt
#SBATCH --error=stderr-%j.txt
#SBATCH --mem=5G
#SBATCH --gres=gpu:1

. ./environment.sh

if [ -z "${SLURM_JOB_NAME}" ]; then
    echo "This script must be run with sbatch:"
    echo "  ./2-initial-submitter"
    exit 1
fi

# do not start "ru-in-container" by default
# but "generator-in-container" instead:

../__gputainer/runvnc $(pwd)/generator-in-container
